### ISSUE TITLE
【建议】新增显示当前文档位置

### ISSUE THREAD

**Issue by bruceOrange22** [chenshinshi/P-Book#1]
您好，很喜欢您做的这个仿书页的主题。有一个显示功能请问可以添加吗？  
![image](https://github.com/chenshinshi/P-Book/assets/26430505/b574e3d8-b02f-4563-ae18-0deb01b98bc0)
如上图，我通过搜索找到了一篇文章并打开了，文章所在的目录结构也自动打开了，但我打开文档标题在左侧没有高亮显示。类似下图这样：  
![image](https://github.com/chenshinshi/P-Book/assets/26430505/bbd5e1b7-5087-423e-820c-36db70e546f5)
请问在后续的主题更新中可以加上这个功能嘛？

**Comment by chenshinshi** [comment]
收到！下个版本更新！
