### ISSUE TITLE
字体怎么设置呢

### ISSUE THREAD

**Issue by SuperNoobTao** [chenshinshi/P-Book#2]
MAC电脑设置默认字体跟随主题，但是好像这个字体没有变成预想的那样
<img width="1174" alt="image" src="https://github.com/chenshinshi/P-Book/assets/16486344/065a3a67-5a4b-4db8-b554-3b45d3bc6911">

<img width="1031" alt="image" src="https://github.com/chenshinshi/P-Book/assets/16486344/ff21c270-21c0-49ce-878a-b47be0dae85e">

**Comment by chenshinshi** [comment]
啊可能mac电脑的引入有问题，因为我没有mac系统无法测试，你先手动安装font文件夹内字体试试，如果不行就直接把字体改成思源宋体就行。
