### ISSUE TITLE
P-Book主题-搜索-替换页面：UI显示看起来错乱

### ISSUE THREAD

**Issue by otto88956** [chenshinshi/P-Book#3]
![image](https://github.com/chenshinshi/P-Book/assets/137133811/43e2c984-c9d0-45df-9eb8-29af68c769d3)
思源笔记版本号：
2.9.3
本地P-Book版本号：
1.34
确认关闭其他代码片段后是否能重现问题：
是
问题描述：
P-Book主题-搜索-替换页面：UI显示有误
复现步骤：
1、P-Book主题-搜索-替换页面：UI显示有误，如图所示
操作系统：
Mac os 13

**Comment by chenshinshi** [comment]
收到，下下个版本更新~
