### ISSUE TITLE
P-Book主题-插件-文档漫游插件页面：文档的标题UI显示不全

### ISSUE THREAD

**Issue by otto88956** [chenshinshi/P-Book#5]
![image](https://github.com/chenshinshi/P-Book/assets/137133811/495dc32c-7304-4ec5-8f4d-9d02db32e8ee)
思源笔记版本号：
2.9.3
本地P-Book版本号：
1.50
确认关闭其他代码片段后是否能重现问题：
是
问题描述：
P-Book主题-插件-文档漫游插件页面：文档的标题UI显示不全
复现步骤：
1、P-Book主题-插件-文档漫游插件页面：文档的标题UI显示不全
2、默认主题、其他主题未发现此问题
3、关闭了其他代码片段后仍然存在
操作系统：
Mac os 13.4

**Comment by chenshinshi** [comment]
这是原作者代码中的mix-blend-mode导致的，这个主题中图片，pdf以及文档标题添加了该代码，其他我已经改成其他样式，但文档标题或许也可以用其他样式去处理，我下个版本修一下吧。
