### ISSUE TITLE
移动端左滑菜单太过透明了

### ISSUE THREAD

**Issue by WingDr** [chenshinshi/P-Book#6]
如下图，这里的opacity感觉调高一点比较合适吧，现在在手机的小屏幕上都看不太清本身的内容了

![146a57cc365e5a114dd07b0a0f3fef2](https://github.com/chenshinshi/P-Book/assets/63407442/a745a545-84fd-43ac-a519-2ea306bc634b)

**Comment by chenshinshi** [comment]
啊我暫時沒想好怎麼分開適配移動端……你可以考慮在移動端手動添加代碼片段將這段背景的顏色改一下，這個設計是爲了搭配背景圖片插件在電腦端實現文檔界面與面板界面的差異化顯示效果。

**Comment by chenshinshi** [comment]
以及推薦移動端使用BHQ mobile，它調大了間距，或者我負責維護的toy主題，它們都很適合手機端的熱區。

**Comment by chenshinshi** [comment]
如有紙張背景的需要我可以考慮下個版本將紙張背景併入toy主題。

**Comment by WingDr** [comment]
okok，我去试试
